# Generated by Django 3.2.25 on 2024-09-28 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='writtenby',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='blog',
            name='written_by',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(default='No content provided'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='heading',
            field=models.CharField(default='Default Heading', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(blank=True, default='https://example.com/default-blog-image.jpg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='country',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(default='No message provided'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phoneno',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(default='Default answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(default='Default question', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='Job description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, default='Open', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='Job Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.URLField(default='https://example.com/default-image.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, default='0000', max_length=4, null=True),
        ),
    ]
