export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const GET_USER='GET_USER'
export const GET_USER_SUCCESS='GET_USER_SUCCESS'
export const GET_USER_FAILED='GET_USER_FAILED'

export const CHECK_USER_SESSION = 'CHECK_USER_SESSION';
export const SET_SIGNED_IN='SET_SIGNED_IN';
export const SET_SIGNED_OUT = 'SET_SIGNED_OUT';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE='SIGN_OUT_FAILURE'
